title: "OpenKerala"
description: "Building Kerala in the open."
baseurl: ""
url: "https://openkerala.org"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  problems:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "problems"
    values:
      layout: "problem"