title: OpenKerala
description: Build Kerala, in the open.
baseurl: "/openkerala"
url: "https://open-kerala.github.io"
theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  problems:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "problems"
    values:
      layout: "problem"